import random

# SCENARIO

# time horizon: 2 weeks
num_time_periods = 2

# shift types list
shift_types = ['morning', 'afternoon', 'night']

# contract types list
contract_types = ['full_time', 'part_time', 'on_call']

# contracts details
contracts = {'full_time': {'min_assignments': 5, 'max_assignments': 12, 'min_cons_working_days': 1, 'max_cons_working_days': 5,
                            'min_cons_days_off': 1, 'max_cons_days_off': 6, 'max_working_week_ends': 2, 'complete_week_ends': False},
            'part_time': {'min_assignments': 8, 'max_assignments': 12, 'min_cons_working_days': 2, 'max_cons_working_days': 6,
                            'min_cons_days_off': 1, 'max_cons_days_off': 5, 'max_working_week_ends': 2, 'complete_week_ends': True},
            'on_call': {'min_assignments': 0, 'max_assignments': 5, 'min_cons_working_days': 1, 'max_cons_working_days': 5,
                            'min_cons_days_off': 1, 'max_cons_days_off': 14, 'max_working_week_ends': 2, 'complete_week_ends': False}
            }

# skills list
skills = ['head_nurse', 'regular_nurse', 'trainee']

# nurses: dictionary of dictionaries
nurses = {0 : {'name': 'Tina', 'contract_type': 'full_time', 'skills': ['head_nurse', 'regular_nurse']},
          1 : {'name': 'Giovanna', 'contract_type': 'part_time', 'skills': ['regular_nurse']},
          2 : {'name': 'Ilaria', 'contract_type': 'on_call', 'skills': ['trainee']},
          3 : {'name': 'Umberto', 'contract_type': 'full_time', 'skills': ['regular_nurse']},
          4 : {'name': 'Ugo', 'contract_type': 'part_time', 'skills': ['trainee']},
          5 : {'name': 'Francesca', 'contract_type': 'full_time', 'skills': ['trainee']},
          6 : {'name': 'Gilberto', 'contract_type': 'full_time', 'skills': ['head_nurse']},
          7 : {'name': 'Elena', 'contract_type': 'part_time', 'skills': ['regular_nurse']},
          8 : {'name': 'Maria', 'contract_type': 'part_time', 'skills': ['trainee']},
          9 : {'name': 'Paolo', 'contract_type': 'on_call', 'skills': ['regular_nurse', 'trainee']},
          10 : {'name': 'Roberta', 'contract_type': 'part_time', 'skills': ['regular_nurse']},
          11 : {'name': 'Franco', 'contract_type': 'full_time', 'skills': ['trainee']},
          12 : {'name': 'Iva', 'contract_type': 'full_time', 'skills': ['regular_nurse']},
          13 : {'name': 'Paola', 'contract_type': 'full_time', 'skills': ['head_nurse']},
          14 : {'name': 'Bianca', 'contract_type': 'on_call', 'skills': ['trainee']},
          15 : {'name': 'Mauro', 'contract_type': 'on_call', 'skills': ['regular_nurse']},
          16 : {'name': 'Francesco', 'contract_type': 'part_time', 'skills': ['trainee']},
          17 : {'name': 'Patrizia', 'contract_type': 'full_time', 'skills': ['trainee']},
          18 : {'name': 'Giada', 'contract_type': 'full_time', 'skills': ['head_nurse']},
          19 : {'name': 'Lorenza', 'contract_type': 'part_time', 'skills': ['regular_nurse']},
          20 : {'name': 'Roberto', 'contract_type': 'part_time', 'skills': ['trainee']},
          21 : {'name': 'Riccardo', 'contract_type': 'on_call', 'skills': ['regular_nurse', 'trainee']},
          22 : {'name': 'Silvia', 'contract_type': 'part_time', 'skills': ['regular_nurse']},
          23 : {'name': 'Angela', 'contract_type': 'full_time', 'skills': ['trainee']},
          24 : {'name': 'Pina', 'contract_type': 'full_time', 'skills': ['head_nurse', 'regular_nurse']},
          25 : {'name': 'Giusi', 'contract_type': 'part_time', 'skills': ['regular_nurse']},
          26 : {'name': 'Chiara', 'contract_type': 'on_call', 'skills': ['trainee']},
          27 : {'name': 'Anna', 'contract_type': 'full_time', 'skills': ['regular_nurse']},
          28 : {'name': 'Annalisa', 'contract_type': 'part_time', 'skills': ['trainee']},
          29 : {'name': 'Ferdinando', 'contract_type': 'full_time', 'skills': ['trainee']},
          30 : {'name': 'Giovanni', 'contract_type': 'full_time', 'skills': ['head_nurse']},
          31 : {'name': 'Mario', 'contract_type': 'part_time', 'skills': ['regular_nurse']},
          32 : {'name': 'Rodolfo', 'contract_type': 'part_time', 'skills': ['trainee']},
          33 : {'name': 'Martina', 'contract_type': 'on_call', 'skills': ['regular_nurse', 'trainee']},
          34 : {'name': 'Viola', 'contract_type': 'part_time', 'skills': ['regular_nurse']},
          35 : {'name': 'Federico', 'contract_type': 'full_time', 'skills': ['trainee']}
        }

# minimum number of consecutive assignments
minimum_consecutive_assignment = {'morning' : 2, 'afternoon' : 3, 'night' : 1}

# maximum number of consecutive assignments
maximum_consecutive_assignment = {'morning' : 3, 'afternoon' : 4, 'night' : 1}

# matrix that represents the shifts succession that are forbidden
forbidden_shifts_succession = {'morning' : {'morning' : False, 'afternoon' : False , 'night' : False},
                               'afternoon' : {'morning' : False, 'afternoon' : False, 'night' : False},
                               'night' : {'morning' : True, 'afternoon' : True, 'night' : True}

                            }

lambdaS1 = 30
lambdaS2_min = 15
lambdaS2_max = 30
lambdaS3 = 30
lambdaS4 = 10
lambdaS5 = 30
lambdaS6 = 20
lambdaS7 = 30

# WEEK-DATA

# single week: 7 days
week = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
days = [day + '-' + str(t) for t in range(num_time_periods) for day in week]

# optimum number of nurses
optimum_nurses = {
    ('Monday-0', 'morning', 'head_nurse'): 1,
    ('Monday-0', 'morning', 'regular_nurse'): 4,
    ('Monday-0', 'morning', 'trainee'): 3,
    ('Monday-0', 'afternoon', 'head_nurse'): 1,
    ('Monday-0', 'afternoon', 'regular_nurse'): 4,
    ('Monday-0', 'afternoon', 'trainee'): 3,
    ('Monday-0', 'night', 'head_nurse'): 1,
    ('Monday-0', 'night', 'regular_nurse'): 4,
    ('Monday-0', 'night', 'trainee'): 5,
    ('Tuesday-0', 'morning', 'head_nurse'): 1,
    ('Tuesday-0', 'morning', 'regular_nurse'): 5,
    ('Tuesday-0', 'morning', 'trainee'): 2,
    ('Tuesday-0', 'afternoon', 'head_nurse'): 1,
    ('Tuesday-0', 'afternoon', 'regular_nurse'): 4,
    ('Tuesday-0', 'afternoon', 'trainee'): 2,
    ('Tuesday-0', 'night', 'head_nurse'): 1,
    ('Tuesday-0', 'night', 'regular_nurse'): 5,
    ('Tuesday-0', 'night', 'trainee'): 5,
    ('Wednesday-0', 'morning', 'head_nurse'): 1,
    ('Wednesday-0', 'morning', 'regular_nurse'): 4,
    ('Wednesday-0', 'morning', 'trainee'): 2,
    ('Wednesday-0', 'afternoon', 'head_nurse'): 1,
    ('Wednesday-0', 'afternoon', 'regular_nurse'): 2,
    ('Wednesday-0', 'afternoon', 'trainee'): 3,
    ('Wednesday-0', 'night', 'head_nurse'): 1,
    ('Wednesday-0', 'night', 'regular_nurse'): 5,
    ('Wednesday-0', 'night', 'trainee'): 4,
    ('Thursday-0', 'morning', 'head_nurse'): 1,
    ('Thursday-0', 'morning', 'regular_nurse'): 5,
    ('Thursday-0', 'morning', 'trainee'): 3,
    ('Thursday-0', 'afternoon', 'head_nurse'): 1,
    ('Thursday-0', 'afternoon', 'regular_nurse'): 3,
    ('Thursday-0', 'afternoon', 'trainee'): 5,
    ('Thursday-0', 'night', 'head_nurse'): 1,
    ('Thursday-0', 'night', 'regular_nurse'): 5,
    ('Thursday-0', 'night', 'trainee'): 3,
    ('Friday-0', 'morning', 'head_nurse'): 1,
    ('Friday-0', 'morning', 'regular_nurse'): 5,
    ('Friday-0', 'morning', 'trainee'): 4,
    ('Friday-0', 'afternoon', 'head_nurse'): 1,
    ('Friday-0', 'afternoon', 'regular_nurse'): 5,
    ('Friday-0', 'afternoon', 'trainee'): 4,
    ('Friday-0', 'night', 'head_nurse'): 1,
    ('Friday-0', 'night', 'regular_nurse'): 2,
    ('Friday-0', 'night', 'trainee'): 5,
    ('Saturday-0', 'morning', 'head_nurse'): 1,
    ('Saturday-0', 'morning', 'regular_nurse'): 4,
    ('Saturday-0', 'morning', 'trainee'): 4,
    ('Saturday-0', 'afternoon', 'head_nurse'): 1,
    ('Saturday-0', 'afternoon', 'regular_nurse'): 5,
    ('Saturday-0', 'afternoon', 'trainee'): 5,
    ('Saturday-0', 'night', 'head_nurse'): 1,
    ('Saturday-0', 'night', 'regular_nurse'): 4,
    ('Saturday-0', 'night', 'trainee'): 4,
    ('Sunday-0', 'morning', 'head_nurse'): 1,
    ('Sunday-0', 'morning', 'regular_nurse'): 3,
    ('Sunday-0', 'morning', 'trainee'): 4,
    ('Sunday-0', 'afternoon', 'head_nurse'): 1,
    ('Sunday-0', 'afternoon', 'regular_nurse'): 2,
    ('Sunday-0', 'afternoon', 'trainee'): 4,
    ('Sunday-0', 'night', 'head_nurse'): 1,
    ('Sunday-0', 'night', 'regular_nurse'): 2,
    ('Sunday-0', 'night', 'trainee'): 2,

    ('Monday-1', 'morning', 'head_nurse'): 1,
    ('Monday-1', 'morning', 'regular_nurse'): 4,
    ('Monday-1', 'morning', 'trainee'): 3,
    ('Monday-1', 'afternoon', 'head_nurse'): 1,
    ('Monday-1', 'afternoon', 'regular_nurse'): 4,
    ('Monday-1', 'afternoon', 'trainee'): 3,
    ('Monday-1', 'night', 'head_nurse'): 1,
    ('Monday-1', 'night', 'regular_nurse'): 4,
    ('Monday-1', 'night', 'trainee'): 5,
    ('Tuesday-1', 'morning', 'head_nurse'): 1,
    ('Tuesday-1', 'morning', 'regular_nurse'): 5,
    ('Tuesday-1', 'morning', 'trainee'): 2,
    ('Tuesday-1', 'afternoon', 'head_nurse'): 1,
    ('Tuesday-1', 'afternoon', 'regular_nurse'): 4,
    ('Tuesday-1', 'afternoon', 'trainee'): 2,
    ('Tuesday-1', 'night', 'head_nurse'): 1,
    ('Tuesday-1', 'night', 'regular_nurse'): 5,
    ('Tuesday-1', 'night', 'trainee'): 5,
    ('Wednesday-1', 'morning', 'head_nurse'): 1,
    ('Wednesday-1', 'morning', 'regular_nurse'): 4,
    ('Wednesday-1', 'morning', 'trainee'): 2,
    ('Wednesday-1', 'afternoon', 'head_nurse'): 1,
    ('Wednesday-1', 'afternoon', 'regular_nurse'): 2,
    ('Wednesday-1', 'afternoon', 'trainee'): 3,
    ('Wednesday-1', 'night', 'head_nurse'): 1,
    ('Wednesday-1', 'night', 'regular_nurse'): 5,
    ('Wednesday-1', 'night', 'trainee'): 4,
    ('Thursday-1', 'morning', 'head_nurse'): 1,
    ('Thursday-1', 'morning', 'regular_nurse'): 5,
    ('Thursday-1', 'morning', 'trainee'): 3,
    ('Thursday-1', 'afternoon', 'head_nurse'): 1,
    ('Thursday-1', 'afternoon', 'regular_nurse'): 3,
    ('Thursday-1', 'afternoon', 'trainee'): 5,
    ('Thursday-1', 'night', 'head_nurse'): 1,
    ('Thursday-1', 'night', 'regular_nurse'): 5,
    ('Thursday-1', 'night', 'trainee'): 3,
    ('Friday-1', 'morning', 'head_nurse'): 1,
    ('Friday-1', 'morning', 'regular_nurse'): 5,
    ('Friday-1', 'morning', 'trainee'): 4,
    ('Friday-1', 'afternoon', 'head_nurse'): 1,
    ('Friday-1', 'afternoon', 'regular_nurse'): 5,
    ('Friday-1', 'afternoon', 'trainee'): 4,
    ('Friday-1', 'night', 'head_nurse'): 1,
    ('Friday-1', 'night', 'regular_nurse'): 2,
    ('Friday-1', 'night', 'trainee'): 5,
    ('Saturday-1', 'morning', 'head_nurse'): 1,
    ('Saturday-1', 'morning', 'regular_nurse'): 4,
    ('Saturday-1', 'morning', 'trainee'): 4,
    ('Saturday-1', 'afternoon', 'head_nurse'): 1,
    ('Saturday-1', 'afternoon', 'regular_nurse'): 5,
    ('Saturday-1', 'afternoon', 'trainee'): 5,
    ('Saturday-1', 'night', 'head_nurse'): 1,
    ('Saturday-1', 'night', 'regular_nurse'): 4,
    ('Saturday-1', 'night', 'trainee'): 4,
    ('Sunday-1', 'morning', 'head_nurse'): 1,
    ('Sunday-1', 'morning', 'regular_nurse'): 3,
    ('Sunday-1', 'morning', 'trainee'): 4,
    ('Sunday-1', 'afternoon', 'head_nurse'): 1,
    ('Sunday-1', 'afternoon', 'regular_nurse'): 2,
    ('Sunday-1', 'afternoon', 'trainee'): 4,
    ('Sunday-1', 'night', 'head_nurse'): 1,
    ('Sunday-1', 'night', 'regular_nurse'): 2,
    ('Sunday-1', 'night', 'trainee'): 2,
}

# minimum number of nurses
minimum_nurses = {
    ('Monday-0', 'morning', 'head_nurse'): 1,
    ('Monday-0', 'morning', 'regular_nurse'): 1,
    ('Monday-0', 'morning', 'trainee'): 2,
    ('Monday-0', 'afternoon', 'head_nurse'): 1,
    ('Monday-0', 'afternoon', 'regular_nurse'): 2,
    ('Monday-0', 'afternoon', 'trainee'): 1,
    ('Monday-0', 'night', 'head_nurse'): 1,
    ('Monday-0', 'night', 'regular_nurse'): 1,
    ('Monday-0', 'night', 'trainee'): 1,
    ('Tuesday-0', 'morning', 'head_nurse'): 1,
    ('Tuesday-0', 'morning', 'regular_nurse'): 2,
    ('Tuesday-0', 'morning', 'trainee'): 2,
    ('Tuesday-0', 'afternoon', 'head_nurse'): 1,
    ('Tuesday-0', 'afternoon', 'regular_nurse'): 1,
    ('Tuesday-0', 'afternoon', 'trainee'): 2,
    ('Tuesday-0', 'night', 'head_nurse'): 1,
    ('Tuesday-0', 'night', 'regular_nurse'): 2,
    ('Tuesday-0', 'night', 'trainee'): 2,
    ('Wednesday-0', 'morning', 'head_nurse'): 1,
    ('Wednesday-0', 'morning', 'regular_nurse'): 2,
    ('Wednesday-0', 'morning', 'trainee'): 2,
    ('Wednesday-0', 'afternoon', 'head_nurse'): 1,
    ('Wednesday-0', 'afternoon', 'regular_nurse'): 1,
    ('Wednesday-0', 'afternoon', 'trainee'): 1,
    ('Wednesday-0', 'night', 'head_nurse'): 1,
    ('Wednesday-0', 'night', 'regular_nurse'): 1,
    ('Wednesday-0', 'night', 'trainee'): 2,
    ('Thursday-0', 'morning', 'head_nurse'): 1,
    ('Thursday-0', 'morning', 'regular_nurse'): 2,
    ('Thursday-0', 'morning', 'trainee'): 2,
    ('Thursday-0', 'afternoon', 'head_nurse'): 1,
    ('Thursday-0', 'afternoon', 'regular_nurse'): 1,
    ('Thursday-0', 'afternoon', 'trainee'): 2,
    ('Thursday-0', 'night', 'head_nurse'): 1,
    ('Thursday-0', 'night', 'regular_nurse'): 2,
    ('Thursday-0', 'night', 'trainee'): 1,
    ('Friday-0', 'morning', 'head_nurse'): 1,
    ('Friday-0', 'morning', 'regular_nurse'): 2,
    ('Friday-0', 'morning', 'trainee'): 2,
    ('Friday-0', 'afternoon', 'head_nurse'): 1,
    ('Friday-0', 'afternoon', 'regular_nurse'): 2,
    ('Friday-0', 'afternoon', 'trainee'): 2,
    ('Friday-0', 'night', 'head_nurse'): 1,
    ('Friday-0', 'night', 'regular_nurse'): 1,
    ('Friday-0', 'night', 'trainee'): 2,
    ('Saturday-0', 'morning', 'head_nurse'): 1,
    ('Saturday-0', 'morning', 'regular_nurse'): 1,
    ('Saturday-0', 'morning', 'trainee'): 2,
    ('Saturday-0', 'afternoon', 'head_nurse'): 1,
    ('Saturday-0', 'afternoon', 'regular_nurse'): 2,
    ('Saturday-0', 'afternoon', 'trainee'): 2,
    ('Saturday-0', 'night', 'head_nurse'): 1,
    ('Saturday-0', 'night', 'regular_nurse'): 2,
    ('Saturday-0', 'night', 'trainee'): 1,
    ('Sunday-0', 'morning', 'head_nurse'): 1,
    ('Sunday-0', 'morning', 'regular_nurse'): 1,
    ('Sunday-0', 'morning', 'trainee'): 2,
    ('Sunday-0', 'afternoon', 'head_nurse'): 1,
    ('Sunday-0', 'afternoon', 'regular_nurse'): 1,
    ('Sunday-0', 'afternoon', 'trainee'): 2,
    ('Sunday-0', 'night', 'head_nurse'): 1,
    ('Sunday-0', 'night', 'regular_nurse'): 1,
    ('Sunday-0', 'night', 'trainee'): 1,

    ('Monday-1', 'morning', 'head_nurse'): 1,
    ('Monday-1', 'morning', 'regular_nurse'): 1,
    ('Monday-1', 'morning', 'trainee'): 2,
    ('Monday-1', 'afternoon', 'head_nurse'): 1,
    ('Monday-1', 'afternoon', 'regular_nurse'): 2,
    ('Monday-1', 'afternoon', 'trainee'): 1,
    ('Monday-1', 'night', 'head_nurse'): 1,
    ('Monday-1', 'night', 'regular_nurse'): 1,
    ('Monday-1', 'night', 'trainee'): 1,
    ('Tuesday-1', 'morning', 'head_nurse'): 1,
    ('Tuesday-1', 'morning', 'regular_nurse'): 2,
    ('Tuesday-1', 'morning', 'trainee'): 2,
    ('Tuesday-1', 'afternoon', 'head_nurse'): 1,
    ('Tuesday-1', 'afternoon', 'regular_nurse'): 1,
    ('Tuesday-1', 'afternoon', 'trainee'): 2,
    ('Tuesday-1', 'night', 'head_nurse'): 1,
    ('Tuesday-1', 'night', 'regular_nurse'): 2,
    ('Tuesday-1', 'night', 'trainee'): 2,
    ('Wednesday-1', 'morning', 'head_nurse'): 1,
    ('Wednesday-1', 'morning', 'regular_nurse'): 2,
    ('Wednesday-1', 'morning', 'trainee'): 2,
    ('Wednesday-1', 'afternoon', 'head_nurse'): 1,
    ('Wednesday-1', 'afternoon', 'regular_nurse'): 1,
    ('Wednesday-1', 'afternoon', 'trainee'): 1,
    ('Wednesday-1', 'night', 'head_nurse'): 1,
    ('Wednesday-1', 'night', 'regular_nurse'): 1,
    ('Wednesday-1', 'night', 'trainee'): 2,
    ('Thursday-1', 'morning', 'head_nurse'): 1,
    ('Thursday-1', 'morning', 'regular_nurse'): 2,
    ('Thursday-1', 'morning', 'trainee'): 2,
    ('Thursday-1', 'afternoon', 'head_nurse'): 1,
    ('Thursday-1', 'afternoon', 'regular_nurse'): 1,
    ('Thursday-1', 'afternoon', 'trainee'): 2,
    ('Thursday-1', 'night', 'head_nurse'): 1,
    ('Thursday-1', 'night', 'regular_nurse'): 2,
    ('Thursday-1', 'night', 'trainee'): 1,
    ('Friday-1', 'morning', 'head_nurse'): 1,
    ('Friday-1', 'morning', 'regular_nurse'): 2,
    ('Friday-1', 'morning', 'trainee'): 2,
    ('Friday-1', 'afternoon', 'head_nurse'): 1,
    ('Friday-1', 'afternoon', 'regular_nurse'): 2,
    ('Friday-1', 'afternoon', 'trainee'): 2,
    ('Friday-1', 'night', 'head_nurse'): 1,
    ('Friday-1', 'night', 'regular_nurse'): 1,
    ('Friday-1', 'night', 'trainee'): 2,
    ('Saturday-1', 'morning', 'head_nurse'): 1,
    ('Saturday-1', 'morning', 'regular_nurse'): 1,
    ('Saturday-1', 'morning', 'trainee'): 2,
    ('Saturday-1', 'afternoon', 'head_nurse'): 1,
    ('Saturday-1', 'afternoon', 'regular_nurse'): 2,
    ('Saturday-1', 'afternoon', 'trainee'): 2,
    ('Saturday-1', 'night', 'head_nurse'): 1,
    ('Saturday-1', 'night', 'regular_nurse'): 2,
    ('Saturday-1', 'night', 'trainee'): 1,
    ('Sunday-1', 'morning', 'head_nurse'): 1,
    ('Sunday-1', 'morning', 'regular_nurse'): 1,
    ('Sunday-1', 'morning', 'trainee'): 2,
    ('Sunday-1', 'afternoon', 'head_nurse'): 1,
    ('Sunday-1', 'afternoon', 'regular_nurse'): 1,
    ('Sunday-1', 'afternoon', 'trainee'): 2,
    ('Sunday-1', 'night', 'head_nurse'): 1,
    ('Sunday-1', 'night', 'regular_nurse'): 1,
    ('Sunday-1', 'night', 'trainee'): 1,
}

# nurse requests: not to work that day in that shift
permit_requests = [(0, 'Saturday-0', 'morning'),
                   (0, 'Saturday-0', 'afternoon'),
                   (0, 'Saturday-0', 'night'),
                   (1, 'Monday-0', 'morning'),
                   (2, 'Tuesday-0', 'afternoon'),
                   (3, 'Friday-0', 'night'),
                   (4, 'Sunday-0', 'morning'),
                   (5, 'Wednesday-0', 'afternoon'),
                   (6, 'Thursday-0', 'morning'),
                   (7, 'Monday-0', 'afternoon'),
                   (8, 'Friday-0', 'morning'),
                   (9, 'Sunday-0', 'night'),
                   (10, 'Thursday-0', 'morning'),
                   (10, 'Thursday-0', 'afternoon'),
                   (10, 'Thursday-0', 'night'),
                   (11, 'Monday-0', 'morning'),
                   (12, 'Saturday-0', 'morning'),
                   (12, 'Saturday-0', 'afternoon'),
                   (12, 'Saturday-0', 'night'),
                   (13, 'Monday-0', 'morning'),
                   (14, 'Tuesday-0', 'afternoon'),
                   (15, 'Friday-0', 'night'),
                   (16, 'Sunday-0', 'morning'),
                   (17, 'Wednesday-0', 'afternoon'),
                   (18, 'Thursday-0', 'morning'),
                   (19, 'Monday-0', 'afternoon'),
                   (20, 'Friday-0', 'morning'),
                   (21, 'Sunday-0', 'night'),
                   (22, 'Thursday-0', 'morning'),
                   (22, 'Thursday-0', 'afternoon'),
                   (22, 'Thursday-0', 'night'),
                   (23, 'Monday-0', 'morning'),
                   (24, 'Saturday-0', 'morning'),
                   (24, 'Saturday-0', 'afternoon'),
                   (24, 'Saturday-0', 'night'),
                   (25, 'Monday-0', 'morning'),
                   (26, 'Tuesday-0', 'afternoon'),
                   (27, 'Friday-0', 'night'),
                   (28, 'Sunday-0', 'morning'),
                   (29, 'Wednesday-0', 'afternoon'),
                   (30, 'Thursday-0', 'morning'),
                   (31, 'Monday-0', 'afternoon'),
                   (32, 'Friday-0', 'morning'),
                   (33, 'Sunday-0', 'night'),
                   (34, 'Thursday-0', 'morning'),
                   (34, 'Thursday-0', 'afternoon'),
                   (34, 'Thursday-0', 'night'),
                   (35, 'Monday-0', 'morning'),

                   (0, 'Saturday-1', 'morning'),
                   (0, 'Saturday-1', 'afternoon'),
                   (0, 'Saturday-1', 'night'),
                   (1, 'Monday-1', 'morning'),
                   (2, 'Tuesday-1', 'afternoon'),
                   (3, 'Friday-1', 'night'),
                   (4, 'Sunday-1', 'morning'),
                   (5, 'Wednesday-1', 'afternoon'),
                   (6, 'Thursday-1', 'morning'),
                   (7, 'Monday-1', 'afternoon'),
                   (8, 'Friday-1', 'morning'),
                   (9, 'Sunday-1', 'night'),
                   (10, 'Thursday-1', 'morning'),
                   (10, 'Thursday-1', 'afternoon'),
                   (10, 'Thursday-1', 'night'),
                   (11, 'Monday-1', 'morning'),
                   (12, 'Saturday-1', 'morning'),
                   (12, 'Saturday-1', 'afternoon'),
                   (12, 'Saturday-1', 'night'),
                   (13, 'Monday-1', 'morning'),
                   (14, 'Tuesday-1', 'afternoon'),
                   (15, 'Friday-1', 'night'),
                   (16, 'Sunday-1', 'morning'),
                   (17, 'Wednesday-1', 'afternoon'),
                   (18, 'Thursday-1', 'morning'),
                   (19, 'Monday-1', 'afternoon'),
                   (20, 'Friday-1', 'morning'),
                   (21, 'Sunday-1', 'night'),
                   (22, 'Thursday-1', 'morning'),
                   (22, 'Thursday-1', 'afternoon'),
                   (22, 'Thursday-1', 'night'),
                   (23, 'Monday-1', 'morning'),
                   (24, 'Saturday-1', 'morning'),
                   (24, 'Saturday-1', 'afternoon'),
                   (24, 'Saturday-1', 'night'),
                   (25, 'Monday-1', 'morning'),
                   (26, 'Tuesday-1', 'afternoon'),
                   (27, 'Friday-1', 'night'),
                   (28, 'Sunday-1', 'morning'),
                   (29, 'Wednesday-1', 'afternoon'),
                   (30, 'Thursday-1', 'morning'),
                   (31, 'Monday-1', 'afternoon'),
                   (32, 'Friday-1', 'morning'),
                   (33, 'Sunday-1', 'night'),
                   (34, 'Thursday-1', 'morning'),
                   (34, 'Thursday-1', 'afternoon'),
                   (34, 'Thursday-1', 'night'),
                   (35, 'Monday-1', 'morning')
                   ]
